version: '3.9'

services:
  es8: 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false

    volumes:
      - es8-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana8:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana8
    environment:
      - node.name=kibana8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      es8:
        condition: service_healthy

volumes:
  es8-data:
    driver: local

networks:
  elastic:
    driver: bridge